import { Category, Provider, Venue, Testimonial } from "./types";

export const SITE_NAME = "ILALI";
export const SITE_TAGLINE = "It takes a village";
export const SITE_DESCRIPTION =
  "Discover and book trusted children's extramural activities in your community. Every provider is background-checked for your peace of mind.";
export const SITE_URL = "https://preview.ilali.co";

export const categories: Category[] = [
  {
    id: "arts-culture",
    name: "Arts & Culture",
    slug: "arts-culture",
    description: "Painting, drawing, pottery, and creative expression",
    icon: "🎨",
    color: "bg-pink-100 text-pink-600",
  },
  {
    id: "sports",
    name: "Sports",
    slug: "sports",
    description: "Football, cricket, swimming, and team sports",
    icon: "⚽",
    color: "bg-blue-100 text-blue-600",
  },
  {
    id: "emotional-intelligence",
    name: "Emotional Intel.",
    slug: "emotional-intelligence",
    description: "Mindfulness, resilience, and emotional growth",
    icon: "🧠",
    color: "bg-purple-100 text-purple-600",
  },
  {
    id: "holiday-programs",
    name: "Holiday Programs",
    slug: "holiday-programs",
    description: "School holiday camps and workshops",
    icon: "🏕️",
    color: "bg-green-100 text-green-600",
  },
  {
    id: "music-lessons",
    name: "Music Lessons",
    slug: "music-lessons",
    description: "Piano, guitar, voice, and instrumental training",
    icon: "🎵",
    color: "bg-amber-100 text-amber-600",
  },
  {
    id: "venues",
    name: "Venues",
    slug: "venues",
    description: "Studios, halls, and outdoor spaces for activities",
    icon: "🏛️",
    color: "bg-indigo-100 text-indigo-600",
  },
  {
    id: "education",
    name: "Education",
    slug: "education",
    description: "STEM, coding, tutoring, and academic support",
    icon: "📚",
    color: "bg-cyan-100 text-cyan-600",
  },
  {
    id: "new-used-equipment",
    name: "New & Used Equipment",
    slug: "equipment",
    description: "Buy and sell activity gear and equipment",
    icon: "🛒",
    color: "bg-orange-100 text-orange-600",
  },
  {
    id: "educational-support",
    name: "Educational Support",
    slug: "educational-support",
    description: "Extra lessons, remedial support, and coaching",
    icon: "✏️",
    color: "bg-teal-100 text-teal-600",
  },
  {
    id: "volunteering",
    name: "Volunteering",
    slug: "volunteering",
    description: "Community service and volunteer opportunities",
    icon: "🤝",
    color: "bg-rose-100 text-rose-600",
  },
  {
    id: "school-open-days",
    name: "School Open Days",
    slug: "school-open-days",
    description: "School tours, open days, and enrollment events",
    icon: "🏫",
    color: "bg-violet-100 text-violet-600",
  },
];

export const providers: Provider[] = [
  {
    id: "1",
    name: "Creative Art Workshop",
    slug: "creative-art-workshop",
    category: "Arts & Culture",
    categorySlug: "arts-culture",
    description: "Explore your creativity through painting, sculpture, and mixed media.",
    providerName: "Art Studio Cape Town",
    location: "Muizenberg",
    distance: "2.5km",
    ageRange: "6-12 years",
    ageMin: 6,
    ageMax: 12,
    rating: 4.8,
    reviewCount: 24,
    price: "R250",
    priceValue: 250,
    priceLabel: "per session",
    image: "",
  },
  {
    id: "2",
    name: "Football Skills Development",
    slug: "football-skills-development",
    category: "Sports",
    categorySlug: "sports",
    description: "Professional football coaching for all skill levels.",
    providerName: "ProKicks Academy",
    location: "Claremont",
    distance: "1.8km",
    ageRange: "8-14 years",
    ageMin: 8,
    ageMax: 14,
    rating: 4.9,
    reviewCount: 45,
    price: "R180",
    priceValue: 180,
    priceLabel: "per session",
    image: "",
    featured: true,
  },
  {
    id: "3",
    name: "Piano & Music Theory",
    slug: "piano-music-theory",
    category: "Music Lessons",
    categorySlug: "music-lessons",
    description: "Learn piano from beginner to advanced with qualified instructors.",
    providerName: "Melody Makers Music School",
    location: "Newlands",
    distance: "3.2km",
    ageRange: "5-16 years",
    ageMin: 5,
    ageMax: 16,
    rating: 5.0,
    reviewCount: 18,
    price: "R350",
    priceValue: 350,
    priceLabel: "per session",
    image: "",
  },
  {
    id: "4",
    name: "STEM Learning Lab",
    slug: "stem-learning-lab",
    category: "Education",
    categorySlug: "education",
    description: "Hand-on science, technology, engineering, and math experiments.",
    providerName: "Future Innovators",
    location: "Rondebosch",
    distance: "4.1km",
    ageRange: "7-13 years",
    ageMin: 7,
    ageMax: 13,
    rating: 4.7,
    reviewCount: 32,
    price: "R280",
    priceValue: 280,
    priceLabel: "per session",
    image: "",
  },
  {
    id: "5",
    name: "Coding for Kids",
    slug: "coding-for-kids",
    category: "Education",
    categorySlug: "education",
    description: "Learn to code with Scratch, Python, and web development.",
    providerName: "Tech Wizards Academy",
    location: "Observatory",
    distance: "3.5km",
    ageRange: "8-15 years",
    ageMin: 8,
    ageMax: 15,
    rating: 4.9,
    reviewCount: 28,
    price: "R300",
    priceValue: 300,
    priceLabel: "per session",
    image: "",
    featured: true,
  },
  {
    id: "6",
    name: "Nature Explorers Club",
    slug: "nature-explorers-club",
    category: "Sports",
    categorySlug: "sports",
    description: "Outdoor adventures, hiking, and nature discovery for kids.",
    providerName: "Wild Adventures SA",
    location: "Constantia",
    distance: "1.2km",
    ageRange: "6-12 years",
    ageMin: 6,
    ageMax: 12,
    rating: 4.9,
    reviewCount: 87,
    price: "R200",
    priceValue: 200,
    priceLabel: "per session",
    image: "",
  },
  {
    id: "7",
    name: "Contemporary Dance Classes",
    slug: "contemporary-dance-classes",
    category: "Arts & Culture",
    categorySlug: "arts-culture",
    description: "Modern dance, ballet, and creative movement for all ages.",
    providerName: "Rhythm & Motion Studio",
    location: "Woodstock",
    distance: "0.8km",
    ageRange: "5-15 years",
    ageMin: 5,
    ageMax: 15,
    rating: 5.0,
    reviewCount: 103,
    price: "R220",
    priceValue: 220,
    priceLabel: "per session",
    image: "",
  },
  {
    id: "8",
    name: "Holiday Adventure Camp",
    slug: "holiday-adventure-camp",
    category: "Holiday Programs",
    categorySlug: "holiday-programs",
    description: "Action-packed school holiday camps with activities and outings.",
    providerName: "Adventure Awaits",
    location: "Hout Bay",
    distance: "5.5km",
    ageRange: "6-14 years",
    ageMin: 6,
    ageMax: 14,
    rating: 4.6,
    reviewCount: 56,
    price: "R1,200",
    priceValue: 1200,
    priceLabel: "per week",
    image: "",
  },
];

export const venues: Venue[] = [
  {
    id: "1",
    name: "Main Theatre",
    slug: "main-theatre",
    type: "studio",
    location: "Newlands",
    rating: 4.5,
    reviewCount: 12,
    image: "",
    capacity: "50 people",
    amenities: ["Stage", "Sound system", "Lighting", "Parking"],
  },
  {
    id: "2",
    name: "Dance Studio",
    slug: "dance-studio",
    type: "studio",
    location: "Claremont",
    rating: 4.5,
    reviewCount: 8,
    image: "",
    capacity: "30 people",
    amenities: ["Mirrors", "Barre", "Wooden floor", "Changing rooms"],
  },
  {
    id: "3",
    name: "Training Fields",
    slug: "training-fields",
    type: "outdoor",
    location: "Newlands",
    rating: 4.5,
    reviewCount: 15,
    image: "",
    capacity: "100+ people",
    amenities: ["Floodlights", "Changing rooms", "Parking", "Canteen"],
  },
  {
    id: "4",
    name: "ILALI Academy Studio",
    slug: "ilali-academy-studio",
    type: "studio",
    location: "Muizenberg",
    rating: 4.5,
    reviewCount: 6,
    image: "",
    capacity: "40 people",
    amenities: ["WiFi", "Projector", "Kitchen", "Garden access"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Lindiwe M.",
    role: "parent",
    location: "Claremont",
    quote:
      "Finally a platform I can trust! My daughter loves her art classes and I love knowing the providers are properly vetted.",
    initial: "L",
  },
  {
    id: "2",
    name: "Sarah K.",
    role: "parent",
    location: "Rondebosch",
    quote:
      "Finding holiday programs used to be such a hassle. ILALI made it so easy to compare options and book in minutes.",
    initial: "S",
  },
  {
    id: "3",
    name: "Thabo R.",
    role: "parent",
    location: "Langa",
    quote:
      "The background checks give me real peace of mind. My son has been going to football practice for 3 months now and loves it.",
    initial: "T",
  },
  {
    id: "4",
    name: "Michelle D.",
    role: "provider",
    location: "Observatory",
    quote:
      "ILALI has transformed how we reach families. Our enrollment has doubled since listing on the platform.",
    initial: "M",
  },
  {
    id: "5",
    name: "James N.",
    role: "provider",
    location: "Muizenberg",
    quote:
      "The booking system is seamless and payments are always on time. Exactly what a small business needs.",
    initial: "J",
  },
];

export const navLinks = [
  { label: "Browse", href: "/browse" },
  { label: "Categories", href: "/categories" },
  { label: "How It Works", href: "/how-it-works" },
];

export const stats = [
  { value: "500+", label: "Providers" },
  { value: "4.8", label: "Avg Rating" },
  { value: "100%", label: "Background Checked" },
  { value: "50+", label: "Activities" },
];
