export const CT_SUBURBS = [
  "Athlone",
  "Bellville",
  "Bergvliet",
  "Bishopscourt",
  "Bloubergstrand",
  "Camps Bay",
  "Cape Town City Centre",
  "Claremont",
  "Constantia",
  "Crawford",
  "Diep River",
  "Durbanville",
  "Fish Hoek",
  "Gardens",
  "Goodwood",
  "Grassy Park",
  "Green Point",
  "Hout Bay",
  "Kenilworth",
  "Khayelitsha",
  "Kommetjie",
  "Lakeside",
  "Langa",
  "Lansdowne",
  "Maitland",
  "Meadowridge",
  "Milnerton",
  "Mitchells Plain",
  "Muizenberg",
  "Newlands",
  "Noordhoek",
  "Observatory",
  "Ottery",
  "Parow",
  "Philippi",
  "Pinelands",
  "Plumstead",
  "Retreat",
  "Rondebosch",
  "Rosebank",
  "Salt River",
  "Sea Point",
  "Simon's Town",
  "Somerset West",
  "Southern Suburbs",
  "St James",
  "Steenberg",
  "Strand",
  "Table View",
  "Tamboerskloof",
  "Tokai",
  "Vredehoek",
  "Vrygrond",
  "Wetton",
  "Woodstock",
  "Wynberg",
  "Zonnebloem",
  "Kalk Bay",
  "Mowbray",
  "Harfield Village",
  "Brooklyn",
] as const;

export type CTSuburb = (typeof CT_SUBURBS)[number];
